### ISSUE TITLE
Clarify the need for my sudo password

### ISSUE THREAD

**Issue by briandant** [appsembler/sultan#7]
After running `make instance.create`, I see the following:

```
Flush Ansible cache...
Reverting made local changes...    [/etc/hosts, ~/.ssh/config]
make[1]: Entering directory '/home/briandant/sultan'
Please enter your sudo password...
make[1]: Leaving directory '/home/briandant/sultan'
[sudo] password for briandant: 
```

Should we clarify why the password is needed and what steps will be taken next? The preceding line's use of `/etc/hosts` and `~/.ssh.config` make me a little nervous about what the script might be up to next.

**Comment by ahmedaljazzar** [comment]
I understand being nervous. Sultan actually doesn't ask for you sudo password, it only prompts you when your local machine needs it.

##### So the question now is, why my local machine always asks for my sudo password when I'm using sultan?

Sultan tries to build a seamless experience between your machine and the remote machine. In order to achieve that, we securely modify you `~/.ssh/config`, `~.ssh/known_hosts`, and `/etc/hosts` files. These configurations can be done manually, but that's frustrating and hard to keep track of. However, through Ansible local deployment we can keep track of these changes and remove them once your machine is destroyed.

As the IP of your remote machine changes when you stop it, we need to reconfigure `~/.ssh/config`, and `/etc/hosts` to match the new IP of your instance after starting it again. On the same hand, `~/.ssh/known_hosts` is being edited to store the fingerprint of you remote machine so that:
- Your local shell doesn't prompt you to trust the remote machine every time you restart it, or re-create it.
- Sometimes, when you remove your machine and create a new one, Google assigns a previously used IP to the newly created machine, but the fingerprint is definitely different, which sends a false positive alert to your local SSH protocol that this newly created machine is tampered or manipulated with.  This alert will prevent you from connecting to the remote machine until you manually remove its record from `~/.ssh/known_hosts`. Sultan automatically manages that for you.

Let me know if you have any idea how to make developers less nervous around that.
